"""
Django settings for careerquest project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m!(1bdxesach4*es$1fd=_@^f$krm45@2=bzeoy&h+g$8c)mrf'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'userapp',
    'employerapp',
    
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'


ROOT_URLCONF = 'careerquest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'userapp','templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'careerquest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'careerquest',
        'USER':'root',
        'PASSWORD':'student',
        'PORT':'3307',
        'HOST':'localhost'
,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_URL = 'login'

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


STATIC_URL = 'static/'
STATICFILES_DIRS = [
    BASE_DIR / "userapp/static",  # Path to your app's static folder
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    'site_title': 'CareerQuest Admin',  # The site title
    'site_header': 'CareerQuest Dashboard',  # The header displayed in the admin panel
    'welcome_sign': 'Welcome to CareerQuest Admin',  # Welcome message
    'show_ui_builder': True,  # Display UI builder (optional)
    'search_model': 'auth.User',  # Model to search by default
    'topmenu_links': [
        {'name': 'Home', 'url': '/', 'icon': 'fas fa-home'},
        {'name': 'Company Profiles', 'url': 'employer_profile/', 'icon': 'fas fa-building'},
        {'name': 'Job Postings', 'url': '/admin/app/jobposting/', 'icon': 'fas fa-briefcase'},
    ],
    'menu': [
        {'name': 'User Management', 'icon': 'fas fa-users', 'children': [
            {'name': 'Users', 'url': '/admin/auth/user/', 'icon': 'fas fa-user-circle'},
            {'name': 'Groups', 'url': '/admin/auth/group/', 'icon': 'fas fa-users-cog'}
        ]},
        {'name': 'Company Management', 'icon': 'fas fa-industry', 'children': [
            {'name': 'Companies', 'url': '/admin/app/employerprofile/', 'icon': 'fas fa-building'},
            {'name': 'Departments', 'url': '/admin/app/department/', 'icon': 'fas fa-cogs'}
        ]},
        {'name': 'Job Management', 'icon': 'fas fa-briefcase', 'children': [
            {'name': 'Job Postings', 'url': '/admin/app/jobposting/', 'icon': 'fas fa-briefcase'},
            {'name': 'Applications', 'url': '/admin/app/jobapplication/', 'icon': 'fas fa-paper-plane'},
        ]},
    ],
    'show_sidebar': True,  # Show sidebar
    'sidebar': [
        {'name': 'Dashboard', 'url': '/', 'icon': 'fas fa-tachometer-alt'},
        {'name': 'Job Postings', 'url': '/admin/app/jobposting/', 'icon': 'fas fa-briefcase'},
        {'name': 'Companies', 'url': '/admin/app/employerprofile/', 'icon': 'fas fa-building'},
        {'name': 'Applications', 'url': '/admin/app/jobapplication/', 'icon': 'fas fa-paper-plane'},
    ],
    'theme': 'dark',  # Choose the color theme (e.g., dark, purple, blue, etc.)
    'header_light': True,  # Set header to be light (True/False)
}
